from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Controller")
        MainWindow.setFixedSize(331, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background:#5b646e;\n"
"color: #f0f1f2;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 0, 121, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(275, 30, 46, 13))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setStyleSheet("QlineEdit{\n"
"color:#5b646e;}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit.setText('192.168.0.15')
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 331, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 0, 2, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 2, 0, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 2, 2, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 1, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 2, 1, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 1, 2, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 1, 1, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 0, 1, 1, 1)
        self.btn_menu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_menu.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_menu.setObjectName("btn_menu")
        self.gridLayout.addWidget(self.btn_menu, 3, 0, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn0.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 3, 1, 1, 1)
        self.btn_return = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_return.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_return.setObjectName("btn_return")
        self.gridLayout.addWidget(self.btn_return, 3, 2, 1, 1)
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_up.setGeometry(QtCore.QRect(130, 290, 75, 41))
        self.btn_up.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_up.setObjectName("btn_up")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(30, 340, 75, 41))
        self.btn_left.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(230, 340, 75, 41))
        self.btn_right.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_right.setObjectName("btn_right")

        self.btn_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_down.setGeometry(QtCore.QRect(130, 390, 75, 41))
        self.btn_down.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_down.setObjectName("btn_down")

        self.btn_enter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enter.setGeometry(QtCore.QRect(130, 340, 75, 41))
        self.btn_enter.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_enter.setObjectName("btn_enter")
        self.btn_smart_hub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_smart_hub.setGeometry(QtCore.QRect(210, 440, 111, 41))
        self.btn_smart_hub.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_smart_hub.setObjectName("btn_smart_hub")
        self.btn_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.btn_off.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_off.setObjectName("btn_off")
        self.btn_html = QtWidgets.QPushButton(self.centralwidget)
        self.btn_html.setGeometry(QtCore.QRect(94, 0, 81, 31))
        self.btn_html.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_html.setObjectName("btn_html")
        self.btn_tools = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tools.setGeometry(QtCore.QRect(0, 442, 121, 41))
        self.btn_tools.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_tools.setObjectName("btn_tools")
        self.btn_mns = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mns.setGeometry(QtCore.QRect(0, 270, 51, 41))
        self.btn_mns.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_mns.setObjectName("btn_mns")
        self.btn_pls = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pls.setGeometry(QtCore.QRect(280, 270, 51, 41))
        self.btn_pls.setStyleSheet("QPushButton{   \n"
"      width: 100%;   \n"
"      font-size: 15px;    \n"
"      border: 0 solid rgba(255, 255, 255, 0.5);   \n"
"      position: relative;  \n"
"      display: inline-block;  \n"
"      font-size: 90%;  \n"
"      font-weight: 700;  \n"
"      color: rgb(209,209,217);  \n"
"      text-decoration: none;  \n"
"      text-shadow: 0 -1px 2px rgba(0,0,0,.2);  \n"
"      padding: .5em 1em;  \n"
"      outline: none;  \n"
"      border-radius: 3px;  \n"
"      background: #29323c;  \n"
"      box-shadow:  \n"
"     0 1px rgba(255,255,255,.2) inset,  \n"
"     0 1px 2px rgba(0,1,6,.5),  \n"
"     0 0 1px 1px rgba(0,1,6,.2);  \n"
"\n"
" }  \n"
"   \n"
" QPushButton:hover{  \n"
"     background: #dbdbdb;  \n"
"    color: #29323c;  \n"
" }  \n"
"   \n"
" QPushButton:pressed{  \n"
"      top: 1px;  \n"
"   background: linear-gradient(rgb(76,77,82), rgb(57,58,65)) rgb(76,77,82);  \n"
"   box-shadow:  \n"
"    0 0 1px rgba(0,0,0,.5) inset,  \n"
"    0 2px 3px rgba(0,0,0,.5) inset,  \n"
"    0 1px 1px rgba(255,255,255,.1);  \n"
"     color: #dbdbdb;  \n"
" } ")
        self.btn_pls.setObjectName("btn_pls")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn_menu.setText(_translate("MainWindow", "Menu"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn_return.setText(_translate("MainWindow", "Return"))
        self.btn_up.setText(_translate("MainWindow", "▲"))
        self.btn_left.setText(_translate("MainWindow", "<"))
        self.btn_right.setText(_translate("MainWindow", ">"))
        self.btn_down.setText(_translate("MainWindow", "▼"))
        self.btn_enter.setText(_translate("MainWindow", "Enter"))
        self.btn_smart_hub.setText(_translate("MainWindow", "SmartHub"))
        self.btn_off.setText(_translate("MainWindow", "OFF"))
        self.btn_html.setText(_translate("MainWindow", "HDMI"))
        self.btn_tools.setText(_translate("MainWindow", "Tools"))
        self.btn_mns.setText(_translate("MainWindow", "-"))
        self.btn_pls.setText(_translate("MainWindow", "+"))